/**
 * Do not edit this file.
 *
 * A Key wraps an integer that you cannot read. 
 * The only way to learn anything about the ordering of two keys is compareTo(Key),
 * and the only way to swap two keys in an array is swap(Key[], int, int). 
 * You must use both of these methods in your sort -- they count how many times they
 * are called, which is how the autograder checks the efficiency of your algorithm.
 *
 * Keys are compared by value but are not equal by value: equals and hashCode are 
 * inherited from Object, so two keys are equal only if they are the same object. 
 * That lets the autograder verify that your sort rearranges the array you were given
 * instead of building a new one.
 */
public final class Key implements Comparable<Key> {

    private static long comparisons = 0L;
    private static long swaps = 0L;
    private final int value;

    private Key(int value) {
        this.value = value;
    }

    /**
     * Compares this key with another. Every call is counted.
     * Use this method for every element comparison in your sort.
     *
     * @param other the key to compare against; must not be null
     * @return a negative number if this key is less than other, zero if they are equal in
     *         value, a positive number if this key is greater
     */
    @Override
    public int compareTo(Key other) {
        comparisons++;
        return Integer.compare(this.value, other.value);
    }

    /**
     * Swaps array elements at positions i and j. Every call is counted.
     * Use this method for every element movement in your sort.
     *
     * @param a the array to modify
     * @param i an index into the array
     * @param j an index into the array
     */
    public static void swap(Key[] a, int i, int j) {
        swaps++;
        Key tmp = a[i];
        a[i] = a[j];
        a[j] = tmp;
    }

    /**
     * Builds an array of keys from the given values. This is the only way to create keys.
     *
     * @param values the values to wrap, in order
     * @return a new array of keys, one per value
     */
    public static Key[] arrayOf(int... values) {
        Key[] keys = new Key[values.length];
        for (int i = 0; i < values.length; i++) {
            keys[i] = new Key(values[i]);
        }
        return keys;
    }

    /** Resets both counters to zero. Called by the test harness; do not call it from your sort. */
    public static void resetCounters() {
        comparisons = 0L;
        swaps = 0L;
    }

    /** @return the number of calls to {@link #compareTo(Key)} since the last reset */
    public static long comparisons() {
        return comparisons;
    }

    /** @return the number of calls to {@link #swap(Key[], int, int)} since the last reset */
    public static long swaps() {
        return swaps;
    }

    /** @return the wrapped value, for debugging only */
    @Override
    public String toString() {
        return Integer.toString(value);
    }
}
